spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    schema-registry:
      url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

  main:
    web-application-type: reactive

server:
  port: ${SERVER_PORT:8080}

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
